### ISSUE TITLE
Update pull request URLs to work with new repo

### ISSUE THREAD

**Issue by fulldecent** [acls-training-center/rnmobility.com#1]

**Comment by robgarza** [comment]
@fulldecent , got it. So far, I have sent an email to GitHub. They have not replied. I will keep digging on my own.

**Comment by willmedtrainingsolutionscom** [comment]
What do you need GitHub involved for?

**Comment by robgarza** [comment]
The articles they provided were not useful, I need clarification.

**Comment by willmedtrainingsolutionscom** [comment]
Here is a direct edit link to edit one specific page on our other repository:

> https://github.com/fulldecent/mtssites/edit/master/CONTRIBUTING.md

To resolve the issue here you can modify this link and include it in the template here.

**Comment by robgarza** [comment]
I was told this issue is good to close. https://github.com/fulldecent/mtssites/issues/881#issuecomment-558711954
