### ISSUE TITLE
Create Branch for redesign

### ISSUE THREAD

**Issue by codiini** [acls-training-center/rnmobility.com#59]
Hi @fulldecent, since I'll be making multiple smaller commits, I think it would be helpful to create a separate branch from the main, say, `website-redesign` so I can merge all my tiny commits into that one, and once everything's complete, I can merge into main.

**Comment by fulldecent** [comment]
You are welcome to manage the commits on your fork as you like.

You can make one PR for your website-redesign branch now. You can discuss in there about any questions or review topics for the redesign. (Attach screenshots often!)

But we update our websites usually every day or two. So you should also be comfortable also sending some changes as shorter PRs that we can publish and review piecemeal.

**Comment by fulldecent** [comment]
And to clarify, not just "multiple smaller commits" but "multiple smaller PRs"
