### ISSUE TITLE
Private/Unavilable Youtube Video  

### ISSUE THREAD

**Issue by codiini** [acls-training-center/rnmobility.com#63]
On the [Licensure Compact Page](https://rnmobility.com/nursinglicensurecompact.html), there is a private/unavailable embedded YouTube video.

![image](https://github.com/user-attachments/assets/e5d17f0b-3d87-4cd1-aee8-d66be1aea7c1)

cc @fulldecent

**Comment by fulldecent** [comment]
This is basically this video https://www.youtube.com/watch?v=4Rl2TNAyHDQ

**Comment by codiini** [comment]
Awesome, thank you.
