### ISSUE TITLE
Update header/footer

### ISSUE THREAD

**Issue by fulldecent** [acls-training-center/rnmobility.com#71]
This website is part of the acls.net network of websites.

Please see the header and footer on acls.net, aclsCertification.ca which are specifically for enrolling students in ACLS courses.

Somehow we should steal that header and adapt it here on this site. Maybe: keep courses, resources; delete algos, accreditations, login, signup; add multi-state licenses, about.

And in the resources under EMT practice add "RN state licensing" which links to the RNMobility homepage.

And then the footer: keep courses, resources; remove rest; add a "About" section just with the RN Mobility "About" page, the "Multi-state licensure"; add the "Contact us" to link to https://www.acls.net/contact.

And then the byline at bottom just steal the existing acls.net byline and keep links to those pages across to acls.net.

---

This is the work that was started in https://github.com/acls-training-center/rnmobility.com/pull/58

---

# Follow on work (separate issue when done)

- [x] Update acls.net and aclsCertification.ca header to add in the resources under EMT practice add "RN state licensing" which links to the RNMobility homepage.

**Comment by Raza403** [comment]
Published new header and footer. Made a new issue https://github.com/modern-training-solutions/public-websites/issues/8067 for follow on work as directed.
